#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint-staged..."
npx lint-staged || exit 1

echo "Checking formatting..."
yarn format:check || exit 1

echo "Building project..."
yarn build || exit 1